###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Who is GOAT?",
    "author": "Ronaldo",
    "url": "https://cristianoronaldo.com/#cr7",
    "likes": 999
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
Content-Type: application/json

# {
#     "username": "GOAT",
#     "name": "Ronaldo",
#     "password": "sui"
# }

{
    "username": "viceGOAT",
    "name": "Messi",
    "password": "sewii"
}