###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "go",
    "name": "Ronaldo",
    "password": "sui"
}

# {
#     "username": "GOAT",
#     "name": "Ronaldo",
#     "password": "sui"
# }

# {
#     "username": "viceGOAT",
#     "name": "Messi",
#     "password": "sewii"
# }