###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "GOAT",
    "name": "Ronaldo",
    "password": "sui"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "viceGOAT",
    "name": "Messi",
    "password": "sewii"
}