###
GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/6a62d124be03688f28fe5ef0
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Full Stack Open is easy",
  "important": true
}

###
DELETE  http://localhost:3001/api/notes/6a656618b576564e830adb15