###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Kevin",
  "number": 997
}
###
PUT http://localhost:3001/api/persons/6a66bcb75684cb1530a9acda
Content-Type: application/json

{
  "name": "Kevin",
  "number": 998
}


###
DELETE  http://localhost:3001/api/persons/6a66ef247dff61bc3d486b9e